In [228]:
#importing required pacakges 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [178]:
#import the data
data = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [179]:
#exploring our data
data.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [180]:
data.tail(10)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
289  90.0        1                       337         0                 38   
290  45.0        0                       615         1                 55   
291  60.0        0                       320         0                 35   
292  52.0        0                       190         1                 38   
293  63.0        1                       103         1                 35   
294  62.0        0                        61         1                 38   
295  55.0        0                      1820         0                 38   
296  45.0        0                      2060         1                 60   
297  45.0        0                      2413         0                 38   
298  50.0        0                       196         0                 45   

     high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
289                    0   390000.0               0.9           144    0   
290                    0   222000.0               0.8           141    0   
291                    0   133000.0               1.4           139    1   
292                    0   382000.0               1.0           140    1   
293                    0   179000.0               0.9           136    1   
294                    1   155000.0               1.1           143    1   
295                    0   270000.0               1.2           139    0   
296                    0   742000.0               0.8           138    0   
297                    0   140000.0               1.4           140    1   
298                    0   395000.0               1.6           136    1   

     smoking  time  DEATH_EVENT  
289        0   256            0  
290        0   257            0  
291        0   258            0  
292        1   258            0  
293        1   270            0  
294        1   270            0  
295        0   271            0  
296        0   278            0  
297        1   280            0  
298        1   285            0

In [181]:
#data.describe()

### Data Pre-processing

In [182]:
#fron=colun
x = data.iloc[:,:-1].values
x.shape

(299, 12)

In [183]:
y = data.iloc[:,12].values
#y.reshape(-1,1)
y
y.shape

(299,)

### Splitting dataset

In [198]:
x_train, x_test, y_train, y_test = train_test_split (x,y, train_size = 0.3)


In [199]:
x_train

array([[ 54.,   0., 582., ...,   1.,   0., 213.],
       [ 62.,   1., 655., ...,   0.,   0., 233.],
       [ 48.,   1., 582., ...,   0.,   0.,  15.],
       ...,
       [ 61.,   1.,  80., ...,   1.,   0., 213.],
       [ 52.,   1., 191., ...,   1.,   1., 216.],
       [ 70.,   0.,  81., ...,   0.,   0., 212.]])

In [197]:
x_train.reshape(-1,1)

array([[ 45.],
       [  0.],
       [582.],
       ...,
       [  1.],
       [  1.],
       [240.]])

In [200]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0], dtype=int64)

In [195]:
y_train.reshape(-1,1)

array([[0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
    

In [185]:
x_train.shape

(89, 12)

In [186]:
y_train.shape

(89,)

In [187]:
#x_train= x_train.to_numpy().reshape(-1, 1)
#x_test = x_train.to_numpy().reshape(-1, 1)


In [211]:
##lets try linear regression first
#regre = LinearRegression()
reg = LogisticRegression(solver='lbfgs', max_iter=100)
#convergence error
#https://stackoverflow.com/questions/62658215/convergencewarning-lbfgs-failed-to-converge-status-1-stop-total-no-of-iter

### Fit our model

In [209]:
#model = regre.fit(x_train, y_train)
model = reg.fit(x_train, y_train)

In [210]:
model.classes_
#number of classes

array([0, 1], dtype=int64)

In [216]:
#model coefficient
model.coef_

array([[ 2.86213065e-02, -1.54439940e-03,  1.54532989e-04,
        -1.16884902e-03, -2.69881611e-02, -4.40911739e-04,
        -2.14190524e-06,  9.43552024e-03,  5.86686615e-03,
         1.06989499e-04, -1.13377106e-03, -1.54259747e-02]])

In [206]:
data.head(10)

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   
5  90.0        1                        47         0                 40   
6  75.0        1                       246         0                 15   
7  60.0        1                       315         1                 60   
8  65.0        0                       157         0                 65   
9  80.0        1                       123         0                 35   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   
5                    1  204000.00               2.1           132    1   
6                    0  127000.00               1.2           137    1   
7                    0  454000.00               1.1           131    1   
8                    0  263358.03               1.5           138    0   
9                    1  388000.00               9.4           133    1   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1  
5        1     8            1  
6        0    10            1  
7        1    10            1  
8        0    10            1  
9        1    10            1

In [222]:
#prediction on train data
pred = model.predict(x_test)

Make prediction with predict_proba()

In [225]:
#predict_proba() returns probabilities of a classification
model.predict_proba(x_test[:5])

array([[0.68829365, 0.31170635],
       [0.66649143, 0.33350857],
       [0.32794953, 0.67205047],
       [0.39628195, 0.60371805],
       [0.89276888, 0.10723112]])

In [226]:
model.predict(x_test[:5])

array([0, 0, 1, 1, 0], dtype=int64)

In [224]:
#Accuracy testing
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8523809523809524